name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "packages/container/**"
# SETS EXECUTION INSIDE CONTAINER DIRECTORY
defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 #LOADS/CHECKOUT OUR CODE TO THE VM
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2 #GIVE PROGRAMATIC ACCESS TO AWS CLI
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest #SYNC/STORE CONTENT OF DIST TO AWS BUCKET
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
